apiVersion: openstack.crossplane.io/v1alpha1
kind: HealthMonitor
metadata:
  name: example-health-monitor
spec:
  forProvider:
    poolId: <pool-id>
    type: HTTP
    delay: 10
    timeout: 5
    maxRetries: 3
    urlPath: /
    httpMethod: GET
    expectedCodes: "200"
    adminStateUp: true
  providerConfigRef:
    name: default
  deletionPolicy: Delete
