/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

// GetItems of this ContainerV1List.
func (l *ContainerV1List) GetItems() []*ContainerV1 {
	items := make([]*ContainerV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this OrderV1List.
func (l *OrderV1List) GetItems() []*OrderV1 {
	items := make([]*OrderV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SecretV1List.
func (l *SecretV1List) GetItems() []*SecretV1 {
	items := make([]*SecretV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
