/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=lb.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// Package type metadata.
const (
	CRDGroup   = "lb.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(SchemeGroupVersion,
		&L7RuleV2Parameters{},
		&MonitorV2Parameters{},
		&LoadbalancerV2Parameters{},
		&PoolV2Parameters{},
		&QuotaV2Parameters{},
		&L7PolicyV2Parameters{},
		&MembersV2Parameters{},
		&ListenerV2Parameters{},
		&MemberV2Parameters{},
		&ListenerV2List{},
		&ListenerV2{},
		&PoolV2List{},
		&PoolV2{},
		&L7PolicyV2List{},
		&L7PolicyV2{},
		&LoadbalancerV2List{},
		&LoadbalancerV2{},
	)
	return nil
}
