/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this L7PolicyV2List.
func (l *L7PolicyV2List) GetItems() []*L7PolicyV2 {
	items := make([]*L7PolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this L7RuleV2List.
func (l *L7RuleV2List) GetItems() []*L7RuleV2 {
	items := make([]*L7RuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ListenerV2List.
func (l *ListenerV2List) GetItems() []*enerV2 {
	items := make([]*enerV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this LoadbalancerV2List.
func (l *LoadbalancerV2List) GetItems() []*LoadbalancerV2 {
	items := make([]*LoadbalancerV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this MemberV2List.
func (l *MemberV2List) GetItems() []*MemberV2 {
	items := make([]*MemberV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this MembersV2List.
func (l *MembersV2List) GetItems() []*MembersV2 {
	items := make([]*MembersV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this MonitorV2List.
func (l *MonitorV2List) GetItems() []*MonitorV2 {
	items := make([]*MonitorV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this PoolV2List.
func (l *PoolV2List) GetItems() []*PoolV2 {
	items := make([]*PoolV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QuotaV2List.
func (l *QuotaV2List) GetItems() []*QuotaV2 {
	items := make([]*QuotaV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
