/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this ImageAccessAcceptV2List.
func (l *ImageAccessAcceptV2List) GetItems() []*ImageAccessAcceptV2 {
	items := make([]*ImageAccessAcceptV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ImageAccessV2List.
func (l *ImageAccessV2List) GetItems() []*ImageAccessV2 {
	items := make([]*ImageAccessV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ImageV2List.
func (l *ImageV2List) GetItems() []*ImageV2 {
	items := make([]*ImageV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
