/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=identity.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"

	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Package type metadata.
const (
	CRDGroup   = "identity.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(CRDGroupVersion,
			&EC2CredentialV3{},
			&EC2CredentialV3List{},
			&UserMembershipV3{},
			&UserMembershipV3List{},
			&ApplicationCredentialV3{},
			&ApplicationCredentialV3List{},
			&EndpointV3{},
			&EndpointV3List{},
			&RoleAssignmentV3{},
			&RoleAssignmentV3List{},
			&InheritRoleAssignmentV3{},
			&InheritRoleAssignmentV3List{},
		&ServiceV3List{},
		&ServiceV3{},
		&RoleV3List{},
		&RoleV3{},
		&UserV3List{},
		&UserV3{},
		&ProjectV3List{},
		&ProjectV3{},
		&GroupV3List{},
		&GroupV3{},
	)
	return nil
}
