/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=identity.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// Package type metadata.
const (
	CRDGroup   = "identity.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(SchemeGroupVersion,
		&RoleV3Parameters{},
		&UserV3Parameters{},
		&InheritRoleAssignmentV3Parameters{},
		&ApplicationCredentialV3Parameters{},
		&EndpointV3Parameters{},
		&UserMembershipV3Parameters{},
		&ServiceV3Parameters{},
		&RoleAssignmentV3Parameters{},
		&EC2CredentialV3Parameters{},
		&GroupV3Parameters{},
		&ServiceV3List{},
		&ServiceV3{},
		&RoleV3List{},
		&RoleV3{},
		&UserV3List{},
		&UserV3{},
		&ProjectV3List{},
		&ProjectV3{},
		&GroupV3List{},
		&GroupV3{},
		&ProjectV3Parameters{},
	)
	return nil
}
