/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this ApplicationCredentialV3List.
func (l *ApplicationCredentialV3List) GetItems() []*ApplicationCredentialV3 {
	items := make([]*ApplicationCredentialV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this EC2CredentialV3List.
func (l *EC2CredentialV3List) GetItems() []*EC2CredentialV3 {
	items := make([]*EC2CredentialV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this EndpointV3List.
func (l *EndpointV3List) GetItems() []*EndpointV3 {
	items := make([]*EndpointV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this GroupV3List.
func (l *GroupV3List) GetItems() []*GroupV3 {
	items := make([]*GroupV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this InheritRoleAssignmentV3List.
func (l *InheritRoleAssignmentV3List) GetItems() []*InheritRoleAssignmentV3 {
	items := make([]*InheritRoleAssignmentV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ProjectV3List.
func (l *ProjectV3List) GetItems() []*ProjectV3 {
	items := make([]*ProjectV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RoleAssignmentV3List.
func (l *RoleAssignmentV3List) GetItems() []*RoleAssignmentV3 {
	items := make([]*RoleAssignmentV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RoleV3List.
func (l *RoleV3List) GetItems() []*RoleV3 {
	items := make([]*RoleV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ServiceV3List.
func (l *ServiceV3List) GetItems() []*ServiceV3 {
	items := make([]*ServiceV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this UserMembershipV3List.
func (l *UserMembershipV3List) GetItems() []*UserMembershipV3 {
	items := make([]*UserMembershipV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this UserV3List.
func (l *UserV3List) GetItems() []*UserV3 {
	items := make([]*UserV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
