/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this ConfigurationV1List.
func (l *ConfigurationV1List) GetItems() []*ConfigurationV1 {
	items := make([]*ConfigurationV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this DatabaseV1List.
func (l *DatabaseV1List) GetItems() []*DatabaseV1 {
	items := make([]*DatabaseV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this InstanceV1List.
func (l *InstanceV1List) GetItems() []*InstanceV1 {
	items := make([]*InstanceV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this UserV1List.
func (l *UserV1List) GetItems() []*UserV1 {
	items := make([]*UserV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
