/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

package controller

import (
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/qosassociationv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/qosv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/quotasetv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/volumeattachv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/volumetypeaccessv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/volumetypev3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/blockstorage/volumev3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/aggregatev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/flavoraccessv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/flavorv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/instancev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/interfaceattachv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/keypairv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/quotasetv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/servergroupv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/compute/volumeattachv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/containerinfra/clustertemplatev1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/containerinfra/clusterv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/containerinfra/nodegroupv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/db/configurationv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/db/databasev1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/db/instancev1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/db/userv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/dns/recordsetv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/dns/transferacceptv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/dns/transferrequestv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/dns/zonev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/fw/groupv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/fw/policyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/fw/rulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/applicationcredentialv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/ec2credentialv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/endpointv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/groupv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/inheritroleassignmentv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/projectv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/roleassignmentv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/rolev3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/servicev3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/usermembershipv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/identity/userv3"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/images/imageaccessacceptv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/images/imageaccessv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/images/imagev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/keymanager/containerv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/keymanager/orderv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/keymanager/secretv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/l7policyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/l7rulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/listenerv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/loadbalancerv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/membersv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/memberv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/monitorv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/poolv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/lb/quotav2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/addressscopev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/floatingipassociatev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/floatingipv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/networkv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/portforwardingv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/portsecgroupassociatev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/portv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/qosbandwidthlimitrulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/qosdscpmarkingrulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/qosminimumbandwidthrulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/qospolicyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/quotav2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/rbacpolicyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/routerinterfacev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/routerroutev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/routerv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/secgrouprulev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/secgroupv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/subnetpoolv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/subnetroutev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/subnetv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/networking/trunkv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/objectstorage/containerv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/objectstorage/objectv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/objectstorage/tempurlv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/orchestration/stackv1"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/providerconfig"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/sharedfilesystem/securityservicev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/sharedfilesystem/shareaccessv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/sharedfilesystem/sharenetworkv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/sharedfilesystem/sharev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/vpnaas/endpointgroupv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/vpnaas/ikepolicyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/vpnaas/ipsecpolicyv2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/vpnaas/servicev2"
	"github.com/crossplane-contrib/provider-openstack/internal/controller/vpnaas/siteconnectionv2"
	"github.com/crossplane/upjet/pkg/controller"
	"sigs.k8s.io/controller-runtime"
)

// Setup creates all controllers with the supplied logger and adds them to
// the supplied manager.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		qosassociationv3.Setup,
		qosv3.Setup,
		quotasetv3.Setup,
		volumeattachv3.Setup,
		volumetypeaccessv3.Setup,
		volumetypev3.Setup,
		volumev3.Setup,
		aggregatev2.Setup,
		flavoraccessv2.Setup,
		flavorv2.Setup,
		instancev2.Setup,
		interfaceattachv2.Setup,
		keypairv2.Setup,
		quotasetv2.Setup,
		servergroupv2.Setup,
		volumeattachv2.Setup,
		clustertemplatev1.Setup,
		clusterv1.Setup,
		nodegroupv1.Setup,
		configurationv1.Setup,
		databasev1.Setup,
		instancev1.Setup,
		userv1.Setup,
		recordsetv2.Setup,
		transferacceptv2.Setup,
		transferrequestv2.Setup,
		zonev2.Setup,
		groupv2.Setup,
		policyv2.Setup,
		rulev2.Setup,
		applicationcredentialv3.Setup,
		ec2credentialv3.Setup,
		endpointv3.Setup,
		groupv3.Setup,
		inheritroleassignmentv3.Setup,
		projectv3.Setup,
		roleassignmentv3.Setup,
		rolev3.Setup,
		servicev3.Setup,
		usermembershipv3.Setup,
		userv3.Setup,
		imageaccessacceptv2.Setup,
		imageaccessv2.Setup,
		imagev2.Setup,
		containerv1.Setup,
		orderv1.Setup,
		secretv1.Setup,
		l7policyv2.Setup,
		l7rulev2.Setup,
		listenerv2.Setup,
		loadbalancerv2.Setup,
		membersv2.Setup,
		memberv2.Setup,
		monitorv2.Setup,
		poolv2.Setup,
		quotav2.Setup,
		addressscopev2.Setup,
		floatingipassociatev2.Setup,
		floatingipv2.Setup,
		networkv2.Setup,
		portforwardingv2.Setup,
		portsecgroupassociatev2.Setup,
		portv2.Setup,
		qosbandwidthlimitrulev2.Setup,
		qosdscpmarkingrulev2.Setup,
		qosminimumbandwidthrulev2.Setup,
		qospolicyv2.Setup,
		quotav2networking.Setup,
		rbacpolicyv2.Setup,
		routerinterfacev2.Setup,
		routerroutev2.Setup,
		routerv2.Setup,
		secgrouprulev2.Setup,
		secgroupv2.Setup,
		subnetpoolv2.Setup,
		subnetroutev2.Setup,
		subnetv2.Setup,
		trunkv2.Setup,
		containerv1objectstorage.Setup,
		objectv1.Setup,
		tempurlv1.Setup,
		stackv1.Setup,
		providerconfig.Setup,
		securityservicev2.Setup,
		shareaccessv2.Setup,
		sharenetworkv2.Setup,
		sharev2.Setup,
		endpointgroupv2.Setup,
		ikepolicyv2.Setup,
		ipsecpolicyv2.Setup,
		servicev2.Setup,
		siteconnectionv2.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
