/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this AggregateV2List.
func (l *AggregateV2List) GetItems() []*AggregateV2 {
	items := make([]*AggregateV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this FlavorAccessV2List.
func (l *FlavorAccessV2List) GetItems() []*FlavorAccessV2 {
	items := make([]*FlavorAccessV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this FlavorV2List.
func (l *FlavorV2List) GetItems() []*FlavorV2 {
	items := make([]*FlavorV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this InstanceV2List.
func (l *InstanceV2List) GetItems() []*InstanceV2 {
	items := make([]*InstanceV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this InterfaceAttachV2List.
func (l *InterfaceAttachV2List) GetItems() []*InterfaceAttachV2 {
	items := make([]*InterfaceAttachV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this KeypairV2List.
func (l *KeypairV2List) GetItems() []*KeypairV2 {
	items := make([]*KeypairV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QuotasetV2List.
func (l *QuotasetV2List) GetItems() []*QuotasetV2 {
	items := make([]*QuotasetV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ServergroupV2List.
func (l *ServergroupV2List) GetItems() []*ServergroupV2 {
	items := make([]*ServergroupV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this VolumeAttachV2List.
func (l *VolumeAttachV2List) GetItems() []*VolumeAttachV2 {
	items := make([]*VolumeAttachV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
