/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=compute.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// Package type metadata.
const (
	CRDGroup   = "compute.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(SchemeGroupVersion,
		&ServergroupV2Parameters{},
		&InstanceV2Parameters{},
		&KeypairV2Parameters{},
		&AggregateV2Parameters{},
		&QuotasetV2Parameters{},
		&InterfaceAttachV2Parameters{},
		&FlavorAccessV2Parameters{},
		&FlavorV2Parameters{},
		&VolumeAttachV2Parameters{},
		&FlavorV2List{},
		&FlavorV2{},
		&KeypairV2List{},
		&KeypairV2{},
		&InstanceV2List{},
		&InstanceV2{},
	)
	return nil
}
