/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this SecurityserviceV2List.
func (l *SecurityserviceV2List) GetItems() []*SecurityserviceV2 {
	items := make([]*SecurityserviceV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ShareAccessV2List.
func (l *ShareAccessV2List) GetItems() []*ShareAccessV2 {
	items := make([]*ShareAccessV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ShareV2List.
func (l *ShareV2List) GetItems() []*ShareV2 {
	items := make([]*ShareV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SharenetworkV2List.
func (l *SharenetworkV2List) GetItems() []*SharenetworkV2 {
	items := make([]*SharenetworkV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
