/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=sharedfilesystem.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// Package type metadata.
const (
	CRDGroup   = "sharedfilesystem.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(SchemeGroupVersion,
		&SharenetworkV2Parameters{},
		&SecurityserviceV2Parameters{},
		&ShareV2Parameters{},
		&ShareV2List{},
		&ShareV2{},
		&SharenetworkV2List{},
		&SharenetworkV2{},
		&SecurityserviceV2List{},
		&SecurityserviceV2{},
		&ShareAccessV2Parameters{},
	)
	return nil
}
