apiVersion: networking.openstack.m.crossplane.io/v1beta1
kind: RouterInterface
metadata:
  name: example-router-interface
spec:
  forProvider:
    routerId: <router-id>
    type: subnet
    subnetId: <subnet-id>
  providerConfigRef:
    name: default
  deletionPolicy: Delete
