apiVersion: networking.openstack.m.crossplane.io/v1beta1
kind: Router
metadata:
  name: example-router
spec:
  forProvider:
    name: my-router
    adminStateUp: true
    distributed: false
  providerConfigRef:
    name: default
  deletionPolicy: Delete
