apiVersion: networking.openstack.m.crossplane.io/v1beta1
kind: Trunk
metadata:
  name: example-trunk
spec:
  forProvider:
    portId: <parent-port-id>
    name: my-trunk
    adminStateUp: true
  providerConfigRef:
    name: default
  deletionPolicy: Delete
