/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

// GetItems of this ProviderConfigUsageList.
func (p *ProviderConfigUsageList) GetItems() []*ProviderConfigUsage {
	items := make([]*ProviderConfigUsage, len(p.Items))
	for i := range p.Items {
		items[i] = &p.Items[i]
	}
	return items
}