/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

// GetItems of this StackV1List.
func (l *StackV1List) GetItems() []*StackV1 {
	items := make([]*StackV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}