/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this RecordsetV2List.
func (l *RecordsetV2List) GetItems() []*RecordsetV2 {
	items := make([]*RecordsetV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this TransferAcceptV2List.
func (l *TransferAcceptV2List) GetItems() []*TransferAcceptV2 {
	items := make([]*TransferAcceptV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this TransferRequestV2List.
func (l *TransferRequestV2List) GetItems() []*TransferRequestV2 {
	items := make([]*TransferRequestV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ZoneV2List.
func (l *ZoneV2List) GetItems() []*ZoneV2 {
	items := make([]*ZoneV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
