apiVersion: compute.openstack.m.crossplane.io/v1beta1
kind: KeyPair
metadata:
  name: example-keypair
spec:
  forProvider:
    name: my-keypair
    type: ssh
  providerConfigRef:
    name: default
  deletionPolicy: Delete
