/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this ClusterV1List.
func (l *ClusterV1List) GetItems() []*ClusterV1 {
	items := make([]*ClusterV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ClustertemplateV1List.
func (l *ClustertemplateV1List) GetItems() []*ClustertemplateV1 {
	items := make([]*ClustertemplateV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this NodegroupV1List.
func (l *NodegroupV1List) GetItems() []*NodegroupV1 {
	items := make([]*NodegroupV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
