/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this GroupV2List.
func (l *GroupV2List) GetItems() []*GroupV2 {
	items := make([]*GroupV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this PolicyV2List.
func (l *PolicyV2List) GetItems() []*PolicyV2 {
	items := make([]*PolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RuleV2List.
func (l *RuleV2List) GetItems() []*RuleV2 {
	items := make([]*RuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
