/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this EndpointGroupV2List.
func (l *EndpointGroupV2List) GetItems() []*EndpointGroupV2 {
	items := make([]*EndpointGroupV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this IkePolicyV2List.
func (l *IkePolicyV2List) GetItems() []*IkePolicyV2 {
	items := make([]*IkePolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this IpsecPolicyV2List.
func (l *IpsecPolicyV2List) GetItems() []*IpsecPolicyV2 {
	items := make([]*IpsecPolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ServiceV2List.
func (l *ServiceV2List) GetItems() []*ServiceV2 {
	items := make([]*ServiceV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SiteConnectionV2List.
func (l *SiteConnectionV2List) GetItems() []*SiteConnectionV2 {
	items := make([]*SiteConnectionV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
