/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this ContainerV1List.
func (l *ContainerV1List) GetItems() []*ContainerV1 {
	items := make([]*ContainerV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this ObjectV1List.
func (l *ObjectV1List) GetItems() []*ObjectV1 {
	items := make([]*ObjectV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this TempurlV1List.
func (l *TempurlV1List) GetItems() []*TempurlV1 {
	items := make([]*TempurlV1, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
