/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=networking.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"

	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Package type metadata.
const (
	CRDGroup   = "networking.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(CRDGroupVersion,
			&RouterInterfaceV2{},
			&QosMinimumBandwidthRuleV2{},
			&AddressscopeV2{},
			&SecgroupRuleV2{},
			&QuotaV2{},
			&TrunkV2{},
			&RouterRouteV2{},
			&RbacPolicyV2{},
			&FloatingipAssociateV2{},
			&PortSecgroupAssociateV2{},
			&QosBandwidthLimitRuleV2{},
			&SubnetpoolV2{},
			&SubnetRouteV2{},
			&PortforwardingV2{},
			&QosDscpMarkingRuleV2{},
			&FloatingipV2{},
		&PortV2List{},
		&PortV2{},
		&SubnetV2List{},
		&SubnetV2{},
		&NetworkV2List{},
		&NetworkV2{},
		&QosPolicyV2List{},
		&QosPolicyV2{},
		&RouterV2List{},
		&RouterV2{},
		&SecgroupV2List{},
		&SecgroupV2{},
	)
	return nil
}
