/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this AddressscopeV2List.
func (l *AddressscopeV2List) GetItems() []*AddressscopeV2 {
	items := make([]*AddressscopeV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this FloatingipAssociateV2List.
func (l *FloatingipAssociateV2List) GetItems() []*FloatingipAssociateV2 {
	items := make([]*FloatingipAssociateV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this FloatingipV2List.
func (l *FloatingipV2List) GetItems() []*FloatingipV2 {
	items := make([]*FloatingipV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this NetworkV2List.
func (l *NetworkV2List) GetItems() []*NetworkV2 {
	items := make([]*NetworkV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this PortSecgroupAssociateV2List.
func (l *PortSecgroupAssociateV2List) GetItems() []*PortSecgroupAssociateV2 {
	items := make([]*PortSecgroupAssociateV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this PortV2List.
func (l *PortV2List) GetItems() []*PortV2 {
	items := make([]*PortV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this PortforwardingV2List.
func (l *PortforwardingV2List) GetItems() []*PortforwardingV2 {
	items := make([]*PortforwardingV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QosBandwidthLimitRuleV2List.
func (l *QosBandwidthLimitRuleV2List) GetItems() []*QosBandwidthLimitRuleV2 {
	items := make([]*QosBandwidthLimitRuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QosDscpMarkingRuleV2List.
func (l *QosDscpMarkingRuleV2List) GetItems() []*QosDscpMarkingRuleV2 {
	items := make([]*QosDscpMarkingRuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QosMinimumBandwidthRuleV2List.
func (l *QosMinimumBandwidthRuleV2List) GetItems() []*QosMinimumBandwidthRuleV2 {
	items := make([]*QosMinimumBandwidthRuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QosPolicyV2List.
func (l *QosPolicyV2List) GetItems() []*QosPolicyV2 {
	items := make([]*QosPolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QuotaV2List.
func (l *QuotaV2List) GetItems() []*QuotaV2 {
	items := make([]*QuotaV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RbacPolicyV2List.
func (l *RbacPolicyV2List) GetItems() []*RbacPolicyV2 {
	items := make([]*RbacPolicyV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RouterInterfaceV2List.
func (l *RouterInterfaceV2List) GetItems() []*RouterInterfaceV2 {
	items := make([]*RouterInterfaceV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RouterRouteV2List.
func (l *RouterRouteV2List) GetItems() []*RouterRouteV2 {
	items := make([]*RouterRouteV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this RouterV2List.
func (l *RouterV2List) GetItems() []*RouterV2 {
	items := make([]*RouterV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SecgroupRuleV2List.
func (l *SecgroupRuleV2List) GetItems() []*SecgroupRuleV2 {
	items := make([]*SecgroupRuleV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SecgroupV2List.
func (l *SecgroupV2List) GetItems() []*SecgroupV2 {
	items := make([]*SecgroupV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SubnetRouteV2List.
func (l *SubnetRouteV2List) GetItems() []*SubnetRouteV2 {
	items := make([]*SubnetRouteV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SubnetV2List.
func (l *SubnetV2List) GetItems() []*SubnetV2 {
	items := make([]*SubnetV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SubnetpoolV2List.
func (l *SubnetpoolV2List) GetItems() []*SubnetpoolV2 {
	items := make([]*SubnetpoolV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this TrunkV2List.
func (l *TrunkV2List) GetItems() []*TrunkV2 {
	items := make([]*TrunkV2, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
