/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=networking.openstack.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"

	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Package type metadata.
const (
	CRDGroup   = "networking.openstack.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(CRDGroupVersion,
		&RouterInterfaceV2{},
		&RouterInterfaceV2List{},
		&QosMinimumBandwidthRuleV2{},
		&QosMinimumBandwidthRuleV2List{},
		&AddressscopeV2{},
		&AddressscopeV2List{},
		&SecgroupRuleV2{},
		&SecgroupRuleV2List{},
		&QuotaV2{},
		&QuotaV2List{},
		&TrunkV2{},
		&TrunkV2List{},
		&RouterRouteV2{},
		&RouterRouteV2List{},
		&RbacPolicyV2{},
		&RbacPolicyV2List{},
		&FloatingipAssociateV2{},
		&FloatingipAssociateV2List{},
		&PortSecgroupAssociateV2{},
		&PortSecgroupAssociateV2List{},
		&QosBandwidthLimitRuleV2{},
		&QosBandwidthLimitRuleV2List{},
		&SubnetpoolV2{},
		&SubnetpoolV2List{},
		&SubnetRouteV2{},
		&SubnetRouteV2List{},
		&PortforwardingV2{},
		&PortforwardingV2List{},
		&QosDscpMarkingRuleV2{},
		&QosDscpMarkingRuleV2List{},
		&FloatingipV2{},
		&FloatingipV2List{},
		&PortV2List{},
		&PortV2{},
		&SubnetV2List{},
		&SubnetV2{},
		&NetworkV2List{},
		&NetworkV2{},
		&QosPolicyV2List{},
		&QosPolicyV2{},
		&RouterV2List{},
		&RouterV2{},
		&SecgroupV2List{},
		&SecgroupV2{},
	)
	return nil
}
