/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1


// GetItems of this QosAssociationV3List.
func (l *QosAssociationV3List) GetItems() []*QosAssociationV3 {
	items := make([]*QosAssociationV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QosV3List.
func (l *QosV3List) GetItems() []*QosV3 {
	items := make([]*QosV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this QuotasetV3List.
func (l *QuotasetV3List) GetItems() []*QuotasetV3 {
	items := make([]*QuotasetV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this VolumeAttachV3List.
func (l *VolumeAttachV3List) GetItems() []*VolumeAttachV3 {
	items := make([]*VolumeAttachV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this VolumeTypeAccessV3List.
func (l *VolumeTypeAccessV3List) GetItems() []*VolumeTypeAccessV3 {
	items := make([]*VolumeTypeAccessV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this VolumeTypeV3List.
func (l *VolumeTypeV3List) GetItems() []*VolumeTypeV3 {
	items := make([]*VolumeTypeV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this VolumeV3List.
func (l *VolumeV3List) GetItems() []*VolumeV3 {
	items := make([]*VolumeV3, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
